### ISSUE TITLE
Changing default base version?

### ISSUE THREAD

**Issue by markusweigelt** [slub/ocrd_controller#33]
Currently the default ocrd/all base version is `maximum-git`. Should we change this version to `maximum-cuda-git`

https://github.com/slub/ocrd_controller/blob/6c6eb2738a76fbec61272dcb9902e61965b9b2f7/Dockerfile#L3

Is it necessary for us to use the `-git` version? According to the Dockerfile, I don't see any need for it, and I would change the default version to `maximum-cuda`.

**Comment by kba** [comment]
The `-git` is not necessary, these are just aliases, all images do now contain the git repository data.

Whether you want CUDA support depends on whether you have the hardware (GPU) to make use of it. If you do, then this will improve performance of the tensorflow processors.

**Comment by markusweigelt** [comment]
Thank you for your response. Is there a reason why there are so many version designations then? I find this variety of aliases very confusing. Perhaps these could be reduced somewhat as well.

**Comment by kba** [comment]
`-git` is historical, because we did not ship the git repos in the containers for a long time to save space. But now that people do use it (as do you), we cannot get rid of it anymore without breaking deployments or rather users not noticing there is a new version.

The `-cuda` variant has a pretty complex setup and is even larger than the regular `maximum` image. It's also consistent with the `core`/`core-cuda` base images.

The `{mini,medi,maxi}mum` variants will eventually need to go though, since everybody is using `maximum` anyway and we plan to provide slim containers backed by the core network extension soon-ish.

**Comment by bertsky** [comment]
> Currently the default ocrd/all base version is `maximum-git`.

That's just the default, though. It is still useful for building locally. On the CI we usually build for CUDA:
https://github.com/slub/ocrd_controller/blob/6c6eb2738a76fbec61272dcb9902e61965b9b2f7/.github/workflows/publish.yml#L13

We could rename from maximum-git to maximum, but since (as @kba explained) this nowadays is just an alias anyway, we can as well keep it.
